/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_substrate_TestSub */

#ifndef _Included_com_example_substrate_TestSub
#define _Included_com_example_substrate_TestSub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_substrate_TestSub
 * Method:    hookDemo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_substrate_TestSub_hookDemo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
